# BOTSv1 indexes.conf
# Place this file at:
# Linux:   /opt/splunk/etc/apps/botsv1_data_set/default/indexes.conf
# Windows: C:\Program Files\Splunk\etc\apps\botsv1_data_set\default\indexes.conf

[botsv1]
homePath   = $SPLUNK_DB/botsv1/db
coldPath   = $SPLUNK_DB/botsv1/colddb
thawedPath = $SPLUNK_DB/botsv1/thaweddb
disabled = false
frozenTimePeriodInSecs = 377395200
